### ISSUE TITLE
I'm using a snippet of your code in my MIT Licensed plugin is that a problem?

### ISSUE THREAD

**Issue by Kame03** [xDefcon/spigot-ping#9]
Hi, I'm using this snippet of your code I gave you credit for it, but I don't know if there would be any issues with licensing?

https://github.com/Kame03/KPManager/blob/master/src/main/java/in/rs/milivojevic/KPManager/utils/PingUtil.java

**Comment by Kame03** [comment]
I will just write my own code, with my own logic and ways, so I will not need to use this, Issue solved.

**Comment by xDefcon** [comment]
Hello, thanks for informing me.

Please feel free to do whatever you like with the code in this repository.

Thanks for contributing.

**Comment by Kame03** [comment]
Edit: I found GPLv3 license to be more appealing, so I just changed my project license to that, and I can keep using this snippet :)
